version: "3.9"

services:
  app:
    container_name: fastapi
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    volumes:
      - ./application:/application
    ports:
      - "8000:8000"
    command: sh -c "/usr/local/bin/entrypoint.sh"
    env_file:
      - .env
volumes:
  db_data:
